site_name: 케라스 설명서
theme: readthedocs
# theme_dir: theme
docs_dir: sources
repo_url: http://github.com/keras-team/keras
site_url: http://keras.io/
site_description: '파이썬 심층학습 라이브러리 케라스 설명서'

dev_addr: '0.0.0.0:8000'
google_analytics: ['UA-61785484-1', 'keras.io']

pages:
- 대문: index.md
- 왜 케라스인가: why-use-keras.md
- 시작:
  - 순차 모델 소개: getting-started/sequential-model-guide.md
  - 함수형 API 소개: getting-started/functional-api-guide.md
  - 자주 묻는 질문: getting-started/faq.md
- 모델:
  - 케라스 모델에 대해: models/about-keras-models.md
  - Sequential: models/sequential.md
  - Model (함수형 API): models/model.md
- 층:
  - 케라스 층에 대해: layers/about-keras-layers.md
  - 기본 층: layers/core.md
  - 합성곱 층: layers/convolutional.md
  - 풀링 층: layers/pooling.md
  - 국소 연결 층: layers/local.md
  - 순환 층: layers/recurrent.md
  - Embedding 층: layers/embeddings.md
  - 병합 층: layers/merge.md
  - 고급 활성 층: layers/advanced-activations.md
  - 정규화 층: layers/normalization.md
  - 잡음 층: layers/noise.md
  - 층 래퍼: layers/wrappers.md
  - 새로운 케라스 층 작성: layers/writing-your-own-keras-layers.md
- 전처리:
  - 열 전처리: preprocessing/sequence.md
  - 텍스트 전처리: preprocessing/text.md
  - 이미지 전처리: preprocessing/image.md
- 손실: losses.md
- 지표: metrics.md
- 최적화: optimizers.md
- 활성: activations.md
- 콜백: callbacks.md
- 데이터셋: datasets.md
- 응용 망: applications.md
- 백엔드: backend.md
- 초기화: initializers.md
- 정칙화: regularizers.md
- 제약: constraints.md
- 시각화: visualization.md
- Scikit-learn API: scikit-learn-api.md
- 유틸리티: utils.md
- Contributing: contributing.md
